name: flutter_app_utils
description: App utils Designed By Eltanvir
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  hive_flutter: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  very_good_analysis: ^5.1.0
